alias gw='./gradlew'
alias grep='grep --color=auto'
alias config='/usr/bin/git --git-dir=$HOME/.config/cfg/ --work-tree=$HOME'
alias copy='xclip -i -sel clip'
alias dc='docker-compose'
alias a='asdf'
alias curl='curl -sS'
