[user]
name = "Thomas Järvstrand"
email = "tjarvstrand@gmail.com"

[ui]
pager = ":builtin"
merge-editor = "meld"
movement.edit = true

[templates]
log = "builtin_log_compact_full_description"

[template-aliases]
branches = '''
  separate(" ",
    if(current_working_copy, "*", " "),
    format_short_change_id_with_change_offset(self),
    commit_timestamp(self).format("%h %d"),
    self.local_bookmarks(),
    if(description,
      description.first_line(),
      label(if(empty, "empty"), description_placeholder),
    ),
    "\n",
  )
'''

[aliases]
a = ["abandon"]
br = ["log", "--no-graph", "-T", "branches", "-r" ,"bookmarks() | heads(mine()~immutable())"]
d = ["diff"]
e = ["edit"]
l = ["log", "-r::@"]
r = ["rebase"]