#!/usr/bin/env python

from xml.etree import ElementTree
import sys
xml = \
'''    <layout>
      <configItem>
        <name>custom</name>
        <shortDescription>custom</shortDescription>
        <description>Custom Keyboard Layouts</description>
      </configItem>
      <variantList>
        <variant>
          <configItem>
            <name>us-sv-dvorak</name>
            <description>US/SV Dvorak</description>
          </configItem>
        </variant>
      </variantList>
    </layout>
'''

layout = ElementTree.fromstring(xml)

tree = ElementTree.parse(sys.argv[1])
layout_list = tree.find('layoutList')
layouts = layout_list.findall('layout')
layout = [l for l in layouts if l.find('configItem').find('name').text == 'custom']
if layout:
  layout_list.remove(layout[0])
layout_list.append(ElementTree.fromstring(xml))

if len(sys.argv) < 3:
  out = sys.argv[1]
else:
  out = sys.argv[2]

with open(out, 'w') as f:
  f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
  f.write('<!DOCTYPE xkbConfigRegistry SYSTEM "xkb.dtd">\n')
  tree.write(f, encoding = "UTF-8", xml_declaration = False)
  f.write('\n')
