(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.gs\\'" . javascript-mode))
(add-to-list 'auto-mode-alist '("\\.phtml\\'" . javascript-mode))
(add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . javascript-mode))
(add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . javascript-mode))
(add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . javascript-mode))
(add-to-list 'auto-mode-alist '("\\.erb\\'" . javascript-mode))
(add-to-list 'auto-mode-alist '("\\.mustache\\'" . javascript-mode))
(add-to-list 'auto-mode-alist '("\\.djhtml\\'" . javascript-mode))
(add-to-list 'auto-mode-alist '("\\.html?\\'" . javascript-mode))
(add-to-list 'auto-mode-alist '("\\.js\\'" . javascript-mode))
(add-to-list 'auto-mode-alist '("\\.jsx\\'" . javascript-mode))
(add-to-list 'auto-mode-alist '("\\.css\\'" . javascript-mode))
(add-to-list 'auto-mode-alist '("\\.scss\\'" . javascript-mode))
(add-to-list 'auto-mode-alist '("\\.xml\\'" . javascript-mode))

(add-hook 'web-mode-hook
  (lambda ()
  (when (equal web-mode-content-type "javascript")
      (web-mode-set-content-type "jsx"))))

